apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  # select the pod for deploy
  selector:
    matchLabels:
      app: nginx-webserver
  # number of instances
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx-webserver
    spec:
      containers:
      - name: webserver
        image: nginx
        ports:
        - containerPort: 80