name: Release Docker Image

on:
  push:
    tags:
      - 'v*.*.*'   # only run on semver tags like v1.2.3

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/bookservice

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 .

  docker:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version (strip leading v)
        run: |
          RAW_TAG="${{ github.ref_name }}"
          echo "VERSION=${RAW_TAG#v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./application
          file: ./application/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}   # e.g. 1.2.3
            ${{ env.IMAGE_NAME }}:latest
